export enum Collections {
  EVENTS = 'events',
  TASKS = 'tasks',
  CATEGORIES = 'categories',
  PAYMENTS = 'payments',
  PROFILE_DETAILS = 'details',
  GUESTS = 'guests',
  LIST = 'list',
  MANUAL_WISH_LIST = 'registry',
  MANUAL_SHOPPING_LIST = 'shopping',
  RECOMMENDED_SHOPING_LIST = 'shopping/groups/list',
  RECOMMENDED_WISH_LIST = 'registry/groups/list',
  PRODUCTS_LIST = 'items/list',
  PRODUCTS_PARAMETERS = 'shopping/parametrs',
  REGION_DETAILS = 'details/profile',
}
