export const INVALID_LOGIN_ATTEMPT = "INVALID_LOGIN_ATTEMPT";
export const SUCCESS_ACCOUNT_CREATION = "SUCCESS_ACCOUNT_CREATION";
export const LOCALE_KEY = "LOCALE_KEY";
export const EVENT_DETAILS = "EVENT_DETAILS";
