export enum AppRoutes {
  LOGIN = "/login",
  CREATE_PROFILE = "/profile/create",
  ROOT = "/",
  SINGLE_TASK = "/task",
  CREATE_TASK = "/task/create",
  UPDATE_TASK = "/task/update",
  GUESTS_LIST = "/guests/list",
  CREATE_GUEST = "/guests/create",
  UPDATE_GUEST = "/guests/update",
  PAYMENTS_LIST = "/payments/list",
  CREATE_PAYMENT = "/payments/create",
  UPDATE_PAYMENT = "/payments/update",
  PURCHASES_LIST = "/purchases/list",
  PURCHASES_BEST_IDEAS = "/purchases/best-ideas",
  MANUAL_PURCHAES_LIST = "/purchases/manual",
  WEDDING_PROFILE = "/wedding-profile",
  REGION_SETTINGS = "/region-settings",
  DESIGN_SETTINGS = "/design-settings",
  POSTS = "/posts",
  POST = "/post",
  VENDORS = "/vendors",
  SEARCH_VENDORS = "/vendors/search",
  SINGLE_VENDOR = "/vendor",
  CREATE_VENDOR = "/vendors/create",
  UPDATE_VENDOR = "/vendors/update",
  SET_USER_LOCATION = "/location/create",
}
