export enum AppRoutes {
  LOGIN = "/login",
  CREATE_PROFILE = "/profile/create",
  ROOT = "/",
  SINGLE_TASK = "/task",
  GUESTS_LIST = "/guests/list",
  PAYMENTS_LIST = "/payments/list",
  PURCHASES_LIST = "/purchases/list",
  PURCHASES_BEST_IDEAS = "/purchases/best-ideas",
  MANUAL_PURCHAES_LIST = "/purchases/manual",
  WEDDING_PROFILE = "/wedding-profile",
  REGION_SETTINGS = "/region-settings",
  DESIGN_SETTINGS = "/design-settings",
  POSTS = "/posts",
  POST = "/post",
  VENDORS = "/vendors",
  SEARCH_VENDORS = "/vendors/search",
  SINGLE_VENDOR = "/vendor",
}
