export const roles = ["viewer", "assistant", "owner"] as const;
export type Roles = "owner" | "assistant" | "viewer";

export enum RoleActions {
  VIEW_TASKS = "tasks.view",
  CREATE_TASK = "tasks.create",
  DELETE_TASK = "tasks.delete",
  MARK_TASK = "tasks.mark",
  EDIT_TASK = "tasks.edit",
  VIEW_GUEST = "guests.view",
  CREATE_GUEST = "guests.create",
  DELETE_GUEST = "guests.delete",
  EDIT_GUEST = "guests.edit",
  GUEST_STATUS = "guests.edit",
  VIEW_PAYMENTS = "payments.view",
  EDIT_PAYMENTS = "payments.edit",
  DELETE_PAYMENTS = "payments.delete",
  MARK_PAYMENT = "payment.mark",
  CREATE_PURCHASE = "purchase.create",
  DELETE_PURCHASE = "purchase.delete",
  VIEW_PURCHASE = "purchase.view",
  LIKE_PURCHASE = "purchase.like",
  VIEW_SETTINGS = "settings.view",
  VIEW_VENDORS = "vendors.view",
  EDIT_VENDORS = "vendors.edit",
  LIKE_VENDOR = "vendors.like",
  VIEW_GUIDES = "guides.view",
  SPECIFY_EVENT_TITLE = "event-title.specify",
}

export const permissions = {
  owner: [
    RoleActions.VIEW_TASKS,
    RoleActions.VIEW_PURCHASE,
    RoleActions.VIEW_GUEST,
    RoleActions.VIEW_SETTINGS,
    RoleActions.VIEW_PAYMENTS,
    RoleActions.VIEW_GUIDES,
    RoleActions.VIEW_VENDORS,
    RoleActions.DELETE_TASK,
    RoleActions.CREATE_TASK,
    RoleActions.CREATE_PURCHASE,
    RoleActions.DELETE_PURCHASE,
    RoleActions.CREATE_GUEST,
    RoleActions.DELETE_GUEST,
    RoleActions.EDIT_TASK,
    RoleActions.EDIT_GUEST,
    RoleActions.EDIT_PAYMENTS,
    RoleActions.EDIT_VENDORS,
    RoleActions.LIKE_VENDOR,
    RoleActions.LIKE_PURCHASE,
    RoleActions.SPECIFY_EVENT_TITLE,
  ],
  assistant: [
    RoleActions.VIEW_TASKS,
    RoleActions.VIEW_GUEST,
    RoleActions.VIEW_SETTINGS,
    RoleActions.VIEW_PURCHASE,
    RoleActions.VIEW_PAYMENTS,
    RoleActions.VIEW_GUIDES,
    RoleActions.VIEW_VENDORS,
    RoleActions.CREATE_TASK,
    RoleActions.CREATE_GUEST,
    RoleActions.CREATE_PURCHASE,
    RoleActions.CREATE_GUEST,
    RoleActions.EDIT_TASK,
    RoleActions.EDIT_GUEST,
    RoleActions.EDIT_PAYMENTS,
    RoleActions.EDIT_VENDORS,
  ],

  viewer: [
    RoleActions.VIEW_TASKS,
    RoleActions.VIEW_GUEST,
    RoleActions.VIEW_PURCHASE,
    RoleActions.VIEW_PAYMENTS,
    RoleActions.VIEW_GUIDES,
    RoleActions.VIEW_VENDORS,
  ],
};
